services:
  - type: web
    name: herbia-model-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app
    healthCheckPath: /symptoms
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
